### ISSUE TITLE
缺少前置

### ISSUE THREAD

**Issue by qsxzaqq** [JHXSMatthew/projects#1]
Shared

**Comment by qsxzaqq** [comment]
and Core

**Comment by JHXSMatthew** [comment]
运行哪个插件的提示。

**Comment by qsxzaqq** [comment]
BC

**Comment by qsxzaqq** [comment]
import com.mcndsj.JHXSMatthew.Shared.GameManager;
import com.mcndsj.JHXSMatthew.Shared.LobbyManager;

**Comment by qsxzaqq** [comment]
还有问一下LobbyServerSelector 他的服务器缓存在哪里

**Comment by qsxzaqq** [comment]
import com.github.JHXSMatthew.Core;

**Comment by qsxzaqq** [comment]
是BC_RedisConnector插件的

**Comment by JHXSMatthew** [comment]
解决了？有几代版本的更替，有些BC上的的东西是没用的。

**Comment by qsxzaqq** [comment]
没解决

**Comment by qsxzaqq** [comment]
就是缺东西

**Comment by qsxzaqq** [comment]
BCRedisConnector

**Comment by qsxzaqq** [comment]
BungeeControl插件的

**Comment by qsxzaqq** [comment]
然后配置文件和数据库的表能给我一份么

**Comment by qsxzaqq** [comment]
缺的东西我都补上了 比如rbc

**Comment by qsxzaqq** [comment]
import com.mcndsj.BC_RedisConnector.BCRedisConnector;

**Comment by qsxzaqq** [comment]
没有这个

**Comment by JHXSMatthew** [comment]
数据表schema已经找不到了，可以通过SQL语句推算出来。 
所有数据当时按照某部门要求都删除了。

我印象里是有做一个shared的东西为了不一直传SQL的lib。 我找找，找到后发上来。

**Comment by JHXSMatthew** [comment]
找到相关代码了，感觉可以无视，只是三个singleton的SQL driver.  使用了BoneCP作为connection pool。

https://github.com/JHXSMatthew/SQL_Lib

**Comment by qsxzaqq** [comment]
哈哈 我直接自己用java.sql写的

**Comment by qsxzaqq** [comment]
直接替换了那句话
