### ISSUE TITLE
询问插件

### ISSUE THREAD

**Issue by qsxzaqq** [JHXSMatthew/projects#10]
请问YC之前的空岛战争是什么插件

**Comment by JHXSMatthew** [comment]
修改过的SkyWarReloaded。
当时作者停止更新了，就拿来改了改用了。
最近好像有收到Email作者回来更新了。 你可以关注一下。

On 4 Mar 2018, at 4:29 pm, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


请问YC之前的空岛战争是什么插件

**Comment by qsxzaqq** [comment]
我记得前段时SKywars在接手SkyWarReloaded。

**Comment by qsxzaqq** [comment]
配置文件什么的还在么=-= 我配置的头昏

**Comment by JHXSMatthew** [comment]
不在了。 数据当时都被有关部门给……了。

On 4 Mar 2018, at 4:47 pm, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


配置文件什么的还在么=-= 我配置的头昏

**Comment by qsxzaqq** [comment]
这。。

**Comment by qsxzaqq** [comment]
求开源 代码太多了 头疼，Maven仓库都没有

**Comment by JHXSMatthew** [comment]
不记得放哪去了……我找找。

On 4 Mar 2018, at 4:58 pm, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


求开源 代码太多了 头疼，Maven仓库都没有

**Comment by qsxzaqq** [comment]
找到了么?

**Comment by JHXSMatthew** [comment]
hi，
确定找不到了。
非常抱歉

**Comment by Doraemon522** [comment]
凋灵弓版起床战争是什么插件

**Comment by Doraemon522** [comment]
凋灵弓版起床战争是什么插件
