### ISSUE TITLE
战墙

### ISSUE THREAD

**Issue by qsxzaqq** [JHXSMatthew/projects#11]
问一下战前怎么配置有栗子么

**Comment by JHXSMatthew** [comment]
最近忙完回复，有些久远了。

Sent from my iPhone

On 28 May 2018, at 10:04 pm, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


问一下战前怎么配置有栗子么

**Comment by JHXSMatthew** [comment]
Hi,
稍微看了一下代码，设置的过程可以在
https://github.com/JHXSMatthew/TheWalls/blob/master/src/main/java/com/github/JHXSMatthew/Main.java
找到。
最终目的是填满一个https://github.com/JHXSMatthew/TheWalls/blob/master/src/main/java/com/github/JHXSMatthew/Game/GameMap.java

过程：
1.确保你是OP
2.确保战墙地图和lobby地图加载完毕

- wall create <地图名> <显示名称> 创建地图
- wall builder <建筑师名称> 设置建筑师名字
- wall wand 拿到斧子
- 拿着斧子，左键点地图对角线最高点，右键点地图对角线最低点。
俯视图：
A B
C D
左键点A的最高点 右键点D的最高点
- wall bound 设置地图范围

x= 墙的个数
while (x > 0)
 - 对每个要倒塌的墙，左键点墙的最高点，右键点墙的最低点。
 - wall wall， 
x --

y=队伍数量
while ( y > 0)
 - 站在每个队伍的出生点，输入 wall spawn
y--

- wall player <总玩家数> 必须被队伍数整除
- wall walltime <倒塌时间>
- wall percentage <开始人数比例> 
- 站在lobby，输入 wall lobby 设置等待出生点
- wall save 保存完毕

**Comment by qsxzaqq** [comment]
谢谢

**Comment by qsxzaqq** [comment]
提醒一下上次那个BC构建的坑还没完结麻烦完结一下

**Comment by JHXSMatthew** [comment]
大坑…
之前的bc有新的想法 一直没去实现。
有空搞一下，谢谢提醒。

Sent from my iPhone

On 15 Jun 2018, at 11:03 pm, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


提醒一下上次那个BC构建的坑还没完结麻烦完结一下
