### ISSUE TITLE
问一个关于BC的问题

### ISSUE THREAD

**Issue by qsxzaqq** [JHXSMatthew/projects#12]
好奇YC以前那么多子服不卡 压测,怎么解决的,求个说法

**Comment by JHXSMatthew** [comment]
堆硬件，做虚拟化，让几组服务子服跟另外的子服完全隔离。

压测简单的策略检测一下 在bc上屏蔽掉。
触发条件xxx后，限制x分钟单个ip进入次数。

多个bc端分布式部署，一个挂了只掉200个人左右，8000人堆40个bc端。

两个字，砸钱…


Sent from my iPhone

On 16 Jun 2018, at 11:23 pm, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


好奇YC以前那么多子服不卡 压测,怎么解决的,求个说法

**Comment by qsxzaqq** [comment]
难道说是KVM?

**Comment by qsxzaqq** [comment]
BC跨BC?

**Comment by qsxzaqq** [comment]
我做的BC跨BC再次跨会掉线233

**Comment by JHXSMatthew** [comment]
不是，只是多个bc，玩家进的时候均衡到每个bc上去 不嵌套。

Sent from my iPhone

On 17 Jun 2018, at 12:17 am, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


我做的BC跨BC再次跨会掉线233

**Comment by qsxzaqq** [comment]
那子服多了会卡怎么办

**Comment by JHXSMatthew** [comment]
子服多了会卡？

Sent from my iPhone

On 17 Jun 2018, at 12:37 am, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


那子服多了会卡怎么办

**Comment by qsxzaqq** [comment]
emm没卡么

**Comment by qsxzaqq** [comment]
还有那个MOTD压测 亚多了掉ping

**Comment by JHXSMatthew** [comment]
motd自己handle一下，做一下策略就好了。
跟其他压测一样的。

主要是系统防火墙层面控制住就比较方便，当时蒲公英的帮了不少忙。

子服多了不会卡，没影响。

Sent from my iPhone

On 17 Jun 2018, at 12:39 am, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


还有那个MOTD压测 亚多了掉ping

**Comment by qsxzaqq** [comment]
蒲公英的那套麻瓜系统帮了不少? Umm

**Comment by qsxzaqq** [comment]
那叫啥 不知道我佛山有没有

**Comment by JHXSMatthew** [comment]
跟技术小哥搞好关系，重点在调优不在系统好坏。

具体我记得是硬件防火墙上做了好几层优化，挡了类CC的攻击。 bc上我自己做了策略，多开点bc，有时候崩一个才掉200人。防假人，motd也都很好办，主要思路还是控制单个肉鸡进来的量。第一波扛住,后面策略就挡掉了。带宽可能开的比较高吧。外网2G，一般的峰值硬吃都吃得下来的。

你说子服卡的问题，我有点印象了，你有几台机器，机器间通信是什么渠道。 bc有个很大的弊端就是内网带宽吃的非常厉害，当时买了个很好的交换机，可以淘宝一下。

有时候网线坏了也能搞得服务器卡，某个centos的版本还有问题，高并发有个地方没搞好会搞得整个机器网卡炸。


Sent from my iPhone

On 17 Jun 2018, at 12:42 am, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


那叫啥 不知道我佛山有没有

**Comment by qsxzaqq** [comment]
华硕的企业级交换机

**Comment by qsxzaqq** [comment]
那台钢BC的2699V4 4个网口都插了

**Comment by JHXSMatthew** [comment]
Mhm.... 子服卡是什么体现呢？ 我可能没遇到你的情况 还是要慢慢排查的。

Sent from my iPhone

On 17 Jun 2018, at 12:51 am, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


华硕的企业级交换机

**Comment by qsxzaqq** [comment]
就是掉信号... 有些人就1格信号

**Comment by JHXSMatthew** [comment]
就一个bc吗，就一个bc会的。
打了他的脸md5还不承认

Sent from my iPhone

On 17 Jun 2018, at 12:53 am, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


就是掉信号... 有些人就1格信号

**Comment by qsxzaqq** [comment]
4个

**Comment by qsxzaqq** [comment]
糊脸4对IP(贵死了艹艹艹)

**Comment by JHXSMatthew** [comment]
有兴趣留个邮箱吧，这里一直发会打扰到别人。

Sent from my iPhone

On 17 Jun 2018, at 12:55 am, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


糊脸4对IP(贵死了艹艹艹)

**Comment by qsxzaqq** [comment]
嗯好的 16266666@qq.com

**Comment by qsxzaqq** [comment]
你的邮箱是?

**Comment by JHXSMatthew** [comment]
发邮件退信了,是不是错了。

Sent from my iPhone

On 17 Jun 2018, at 1:03 am, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


你的邮箱是?

**Comment by qsxzaqq** [comment]
打错了emmm 

1626666628@qq.com
