### ISSUE TITLE
大佬能看下起床修改的部分嘛，感谢！

### ISSUE THREAD

**Issue by youguo** [JHXSMatthew/projects#17]
邮箱qzz@live.com

**Comment by JHXSMatthew** [comment]
太久了，实在找不到了。

________________________________
From: youguo ***@***.***>
Sent: Wednesday, May 31, 2023 2:31 PM
To: JHXSMatthew/projects ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [JHXSMatthew/projects] 大佬能看下起床修改的部分嘛，感谢！ (Issue #17)


***@***.******@***.***>

―

**Comment by youguo233** [comment]
比较好奇当时服务器怎么带几千个人的QAQ，大致的架构是怎样的呢
用了redisbungee不知道顶层怎么分流玩家，是通过dns动态解析嘛？
