### ISSUE TITLE
缺少BossBarSender插件

### ISSUE THREAD

**Issue by xiaonian233** [JHXSMatthew/projects#2]
在研究uhc时发现缺少BossBarSender插件的import，不知可否分享一下
如果可以的话，就非常感谢了

**Comment by JHXSMatthew** [comment]
大概是BossBar API的一个wrapper。 稍后发上来，需要去掉一些敏感信息。

**Comment by JHXSMatthew** [comment]
https://github.com/JHXSMatthew/BossBarSender
已发出，有问题reopen。

**Comment by xiaonian233** [comment]
谢谢

**Comment by JHXSMatthew** [comment]
不客气，觉得有意思可以start一下。
