### ISSUE TITLE
uhc

### ISSUE THREAD

**Issue by xiaonian233** [JHXSMatthew/projects#3]
uhc的sql结构能否提供，手动恢复失败，感谢非常

**Comment by JHXSMatthew** [comment]
比较久远已经找不到了。
凭着记忆和代码推了一下，应该是这样的：
(`id`,`Name`,`Games`,`Wins`,`Kills`,`Deaths`,`Stacks`,`Points`) 

id::int
Name::varchar(16)
Games:: int
Wins::int
Kills::int
Deaths::int
Stacks::int
Points::int

**Comment by JHXSMatthew** [comment]
CREATE TABLE UHC (
  id Integer PRIMARY KEY AUTO_INCREMENT ,
  Name Varchar(16),
  Games Integer,
  Wins Integer,
  Kills Integer,
  Deaths Integer,
  Stacks Integer,
  Points Integer
);
CREATE INDEX Index_UHC_Name ON UHC (Name);

**Comment by xiaonian233** [comment]
谢谢

**Comment by JHXSMatthew** [comment]
我也没测其实，成功了麻烦说一下，我把它放到readme上。 方便后边的人用。

**Comment by xiaonian233** [comment]
创建成功了，但是同时又出现两个新表一个是WackAmole和BossBarInfo在BossBarSender中的com.github.JHXSMatthew.BossBarSQL中，这个数据结构我创建后，游戏不会读取，请求帮助,感谢

**Comment by JHXSMatthew** [comment]
这两个应该没有任何关系……
可以去掉相关代码 在 bossbar插件里。
wackamole是另外一个插件吧……

游戏加载要求一个world name是lobby

**Comment by xiaonian233** [comment]
好的谢谢，我给uhc加了一些骚操作23333让它更像PUBG233

**Comment by JHXSMatthew** [comment]
愿意开源的话可以创建fork或者直接提交PR
玩的愉快。
代码为了赶项目写的很急，有不清楚的地方可以找我。

Sent from my iPhone

On 21 Feb 2018, at 11:04 pm, whitedew <notifications@github.com<mailto:notifications@github.com>> wrote:


好的谢谢，我给uhc加了一些骚操作23333让它更像PUBG233

**Comment by xiaonian233** [comment]
好的，我现在在尝试在修空投箱子的地图问题，不知道什么原因里面的地图都是空的

**Comment by JHXSMatthew** [comment]
哪个地图是空的？
游戏的逻辑应该是没有任何问题的。


Sent from my iPhone

On 22 Feb 2018, at 1:13 pm, whitedew <notifications@github.com<mailto:notifications@github.com>> wrote:


好的，我现在在尝试在修空投箱子的地图问题，不知道什么原因里面的地图都是空的

**Comment by xiaonian233** [comment]
对，我也发现没有问题但是是空的，我在尝试解决

**Comment by JHXSMatthew** [comment]
是指生成的地图是空的吗？

Sent from my iPhone

On 22 Feb 2018, at 3:59 pm, whitedew <notifications@github.com<mailto:notifications@github.com>> wrote:


对，我也发现没有问题但是是空的，我在尝试解决

**Comment by xiaonian233** [comment]
是的，拿起地图里面是空白

**Comment by JHXSMatthew** [comment]
地图文件夹占硬盘空间是多少？
游戏状态是生成完毕吗？

Sent from my iPhone

On 22 Feb 2018, at 4:25 pm, whitedew <notifications@github.com<mailto:notifications@github.com>> wrote:


是的，拿起地图里面是空白

**Comment by xiaonian233** [comment]
78mb左右，生成完毕了

**Comment by JHXSMatthew** [comment]
用地图编辑器打开看看是否生成完毕。


Sent from my iPhone

On 22 Feb 2018, at 4:57 pm, whitedew <notifications@github.com<mailto:notifications@github.com>> wrote:


是完整的地图我看文件夹写的是78mb左右

**Comment by xiaonian233** [comment]
生成完毕了

**Comment by JHXSMatthew** [comment]
大小是多大？

Sent from my iPhone

On 22 Feb 2018, at 6:49 pm, whitedew <notifications@github.com<mailto:notifications@github.com>> wrote:


生成完毕了

**Comment by JHXSMatthew** [comment]
等下…你说的是手上拿的地图吗。游戏道具 地图？

Sent from my iPhone

On 22 Feb 2018, at 6:49 pm, whitedew <notifications@github.com<mailto:notifications@github.com>> wrote:


生成完毕了

**Comment by xiaonian233** [comment]
233手上拿的地图

**Comment by xiaonian233** [comment]
空的对没错就是空的我按照你那个写法单独写了个给玩家地图依旧是空的

**Comment by JHXSMatthew** [comment]
物品的地图需要设置world
查看spigot相关api
我原来应该没有地图这部分。

Sent from my iPhone

On 22 Feb 2018, at 10:07 pm, whitedew <notifications@github.com<mailto:notifications@github.com>> wrote:


空的对没错就是空的我按照你那个写法单独写了个给玩家地图依旧是空的

**Comment by xiaonian233** [comment]
有呀
![image](https://user-images.githubusercontent.com/21072615/36536633-aaa537d2-1808-11e8-8478-3e57bb6ef1de.png)
com.github.JHXSMatthew.Controller.ChestControl中

**Comment by JHXSMatthew** [comment]
哈哈哈哈哈 这个当时从战墙copy过来的。没怎么动

Sent from my iPhone

On 22 Feb 2018, at 10:44 pm, whitedew <notifications@github.com<mailto:notifications@github.com>> wrote:


有呀
[image]<https://user-images.githubusercontent.com/21072615/36536633-aaa537d2-1808-11e8-8478-3e57bb6ef1de.png>
com.github.JHXSMatthew.Controller.ChestControl中

**Comment by xiaonian233** [comment]
2333好吧

**Comment by xiaonian233** [comment]
看到好像有MapView 里面有setworld的操作

**Comment by xiaonian233** [comment]
老铁我这里还是不行，老铁能否尝试一下？

**Comment by JHXSMatthew** [comment]
好，明天下班之后回家试试。
服务端版本是什么。

Sent from my iPhone

On 23 Feb 2018, at 10:35 pm, whitedew <notifications@github.com<mailto:notifications@github.com>> wrote:


老铁我这里还是不行，老铁能否尝试一下？

**Comment by xiaonian233** [comment]
1.8.8版本谢谢

**Comment by JHXSMatthew** [comment]
前段时间有些忙，我尽快看。

**Comment by xiaonian233** [comment]
好的谢谢

**Comment by xiaonian233** [comment]
作者怎么样了？

**Comment by JHXSMatthew** [comment]
我电脑上已经删除了有关minecraft dev的东西。正在配置开发环境。
最近忙其它项目，可能有所延误。
今天下午我试着看看。


Sent from my iPhone

On 4 Mar 2018, at 9:02 pm, whitedew <notifications@github.com<mailto:notifications@github.com>> wrote:


作者怎么样了？

**Comment by xiaonian233** [comment]
非常感谢

**Comment by JHXSMatthew** [comment]
<img width="757" alt="screen shot 2018-03-05 at 11 56 50 pm" src="https://user-images.githubusercontent.com/11565658/36976242-ffafc1c2-20d0-11e8-8650-a3f577f07300.png">
 地图似乎正常？
拿到手上是否右键过？ 空白地图需要右键。

**Comment by JHXSMatthew** [comment]
Sorry. 才发现插件里写的是map 应该是empty_map .已修复。

**Comment by xiaonian233** [comment]
非常感谢
