### ISSUE TITLE
BCRedisConnector

### ISSUE THREAD

**Issue by qsxzaqq** [JHXSMatthew/projects#5]
LobbyPlayers 表 不报错大厅id,求dalao看看

**Comment by JHXSMatthew** [comment]
完整组织一下语言。在进行哪一步的时候出现了问题？

**Comment by qsxzaqq** [comment]
数据库啥的我都建了

**Comment by qsxzaqq** [comment]
就是LobbyPlayers这个表 他要缓存大厅的id(几号大厅)，然后他填写的是null

**Comment by JHXSMatthew** [comment]
哪个插件里的？我有些忘了。是不是要传送玩家回上一个他在的大厅…

Sent from my iPhone

On 21 Feb 2018, at 2:40 pm, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


就是LobbyPlayers这个表 他要缓存大厅的id(几号大厅)，然后他填写的是null

**Comment by qsxzaqq** [comment]
怼

**Comment by JHXSMatthew** [comment]
我看了一眼代码，缓存的好像是大厅的名字。数据表结构贴一下看看。

Sent from my iPhone

On 21 Feb 2018, at 2:45 pm, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


怼

**Comment by JHXSMatthew** [comment]
比如说有12个walllobby
分别是 walllobby1 walllobby2 .... walllobby12
存储的是walllobby 不是walllobby12
存储那部是先去掉数字，再把名字存进去。

加入的时候拿出名字， 再加上一个递增的数字 顺便就做了一个简易的均衡负载。

可以看一下lobbysend.java 在bc_redisconnector里

Sent from my iPhone

On 21 Feb 2018, at 2:45 pm, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


怼

**Comment by qsxzaqq** [comment]
Name
Lastlobby
id

**Comment by JHXSMatthew** [comment]
lobby的名字是否为全数字？

**Comment by qsxzaqq** [comment]
是的

**Comment by JHXSMatthew** [comment]
格式为
xxxlobby+编号 
比如
uhclobby1
uhclobby2

**Comment by qsxzaqq** [comment]
对

**Comment by qsxzaqq** [comment]
对了还有BungeeConfiguration有什么用

**Comment by qsxzaqq** [comment]
在SQLUtils

**Comment by JHXSMatthew** [comment]
当时做了一个热加载spigot node的方式，通过数据库控制bc的配置，不用重启或者是reload bc就可以加新的spigot服
这个应该就是这个功能的数据表。

**Comment by qsxzaqq** [comment]
LobbyPlayers表结构给我一份

**Comment by JHXSMatthew** [comment]
其实是太懒了，有十几个bc要配置…

**Comment by qsxzaqq** [comment]
我这边6个...

**Comment by qsxzaqq** [comment]
也是每次搞的头大

**Comment by JHXSMatthew** [comment]
你发的应该就是对的，检查lobby的命名方式是否符合。
应该就是lobby名字的问题了，所以写进去了一个null

**Comment by qsxzaqq** [comment]
我就登陆大厅是没有数字的

**Comment by qsxzaqq** [comment]
别的都有

**Comment by qsxzaqq** [comment]
我都是改了的

**Comment by qsxzaqq** [comment]
对了还有那个极限生存退出不了游戏是什么情况

**Comment by JHXSMatthew** [comment]
最好是一个issue一个问题。比较容易理解。
这是写入前拿名字的地方，在
https://github.com/JHXSMatthew/Bc_ServerSelector/blob/master/src/main/java/com/mcndsj/BC_RedisConnector/LobbySend/LobbyController.java


final String type = evt.getServer().getInfo().getName().replace(String.valueOf(id),"");

可以加一个print看看出来的结果是什么。

**Comment by qsxzaqq** [comment]
不知道什么问题不让去大厅

**Comment by qsxzaqq** [comment]
本来是我删了不允许去大厅这句话的

**Comment by qsxzaqq** [comment]
LobbyController

public void onSend(ServerConnectEvent evt){

**Comment by JHXSMatthew** [comment]
等我到家了好好看看，手机上不太方便。
一小时。

Sent from my iPhone

On 21 Feb 2018, at 3:34 pm, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


LobbyController

public void onSend(ServerConnectEvent evt){

**Comment by qsxzaqq** [comment]
好的

**Comment by JHXSMatthew** [comment]
这个不是禁止进lobby
而是发到YouCraft Core单独的程序里去控制。
因为单个bc没有全局信息，每次玩家尝试连接大厅的时候，不太好知道哪个大厅是多少人。redisbungee的解决方案太蠢了，需要便利整个Redis库，如果不便利，那就要在不同的bc上存储全局信息，于是我写了个第三方的控制程序，Core，通过redis的pubsub通讯。
每次玩家尝试加入大厅的时候，发送一个信息到Core里，Core内部有个队列，每一个周期会处理一些请求，发回玩家对应在的bc，通知传送到哪个大厅。
同样的，大厅到游戏的逻辑也是一样的。游戏服务器内的玩家可能来自不同的bc，在全国不同地域的服务器上，bc不参与游戏服务器人数的控制，包括游戏服务器的状态，对bc也是未知的。


Sent from my iPhone

On 21 Feb 2018, at 3:40 pm, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


好的

**Comment by qsxzaqq** [comment]
那个是core

**Comment by qsxzaqq** [comment]
哪个

**Comment by qsxzaqq** [comment]
懂了 也就说我Bukkit上面没装那啥插件

**Comment by qsxzaqq** [comment]
YourCraftCore装置哪里呢？

**Comment by JHXSMatthew** [comment]
是个单独的程序 直接运行
记得装redis

Sent from my iPhone

On 21 Feb 2018, at 4:41 pm, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


YourCraftCore装置哪里呢？

**Comment by qsxzaqq** [comment]
我弄好了
但是Redis里面没有创建别的东西

**Comment by qsxzaqq** [comment]
但是还是卡在登陆大厅不送走

**Comment by qsxzaqq** [comment]
而且获取不正确

**Comment by JHXSMatthew** [comment]
Redis里不会创建新的东西是正常的。只是用了pub sub。
能具体描述一下吗？

Sent from my iPhone

On 21 Feb 2018, at 6:38 pm, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


而且获取不正确

**Comment by qsxzaqq** [comment]
而且获取服务器人数不正常

**Comment by JHXSMatthew** [comment]
是指获取单个spigot服务器人数不正常吗？

**Comment by qsxzaqq** [comment]
对

**Comment by qsxzaqq** [comment]
https://i.loli.net/2018/02/21/5a8d295d5d03b.png

**Comment by JHXSMatthew** [comment]
是否使用了对应的xxx_lobby插件。
比如
uhc_lobby
里面config有个starting port。规定了spigot的端口起始点

Sent from my iPhone

On 21 Feb 2018, at 7:10 pm, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


https://i.loli.net/2018/02/21/5a8d295d5d03b.png

**Comment by qsxzaqq** [comment]
这样的啊=-=

**Comment by JHXSMatthew** [comment]
我记得有个在lobby装的东西… 不记得叫什么了。应该不是上面说的那个。

Sent from my iPhone

On 21 Feb 2018, at 7:16 pm, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


这样的啊=-=

**Comment by qsxzaqq** [comment]
到时候你看看

**Comment by JHXSMatthew** [comment]
似乎也是要装GameServerStatusSync的

看了一眼core的代码和几个lobby plugin的代码。运作模式跟子每个游戏服务器应该是一致的。

spigot流程图
-启动
-通过redis从端获取服务器名称
-获取完毕后向core发送heartbeat 服务器上线
-等待玩家加入，持续发送hearbeat防掉线
-加入过程中优化
-满人发送drop，开始游戏

大厅的服务端操作不太一样，不会直接drop 还是会继续监听。我一会儿翻翻代码库，是不是当时单独写了一个给大厅用。


Sent from my iPhone

On 21 Feb 2018, at 7:20 pm, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


到时候你看看

**Comment by qsxzaqq** [comment]
=-=

**Comment by qsxzaqq** [comment]
到时候我做起床的时候是调用他的事件么

**Comment by JHXSMatthew** [comment]
模仿uhc即可，call一个game event。
你要用这套架构？

Sent from my iPhone

On 21 Feb 2018, at 8:05 pm, qsxzaqq <notifications@github.com<mailto:notifications@github.com>> wrote:


到时候我做起床的时候是调用他的事件么

**Comment by qsxzaqq** [comment]
对

**Comment by qsxzaqq** [comment]
这套构建特别时候我服务器
