### ISSUE TITLE
YourCraftCore

### ISSUE THREAD

**Issue by qsxzaqq** [JHXSMatthew/projects#8]
这样正常么
![image](https://i.loli.net/2018/02/26/5a93d5f6c42ed.png)

**Comment by qsxzaqq** [comment]
这样的话 主大厅可以匹配但是起床大厅不行

**Comment by JHXSMatthew** [comment]
不能匹配是指什么意思呢？
无法从游戏大厅到对应游戏吗？

**Comment by qsxzaqq** [comment]
无法匹配到二号游戏大厅

**Comment by qsxzaqq** [comment]
主大厅可以匹配
